### ISSUE TITLE
[common.toml]Allow mobs break block

### ISSUE THREAD

**Issue by bz001** [BuiltBrokenModding/AI-Improvements#19]
#Black/Whitelist for various stuff
[list]
	#By default the mod only modifies EntityMobs. Add other entities here if you want to apply modifications to them. Usage:
	#<entity registry name> followed by any of:
	#[ALL,ATTRIBUTES,ARMOR,HELDITEMS,BLOCKBREAK,USEITEM,LADDER,STEAL,SWIMMRIDE,TARGETVILLAGER,REVERSE].

How can I use this,can u give me a example?Thanks!

**Comment by bl4ckscor3** [comment]
That's not a configuration option from AI Improvements.

**Comment by bz001** [comment]
> 这不是AI Improvements的配置选项。

so could this mod allow mobs break block?

**Comment by bl4ckscor3** [comment]
That's not in the scope of this mod.
