### ISSUE TITLE
Crash: Cannot read field "callCount" because "m" is null

### ISSUE THREAD

**Issue by simeonpfeiffer** [BuiltBrokenModding/AI-Improvements#21]
The server crashed while noone was playing.

`java.lang.NullPointerException: Cannot read field "callCount" because "m" is null`

[crash report.txt](https://github.com/BuiltBrokenModding/AI-Improvements/files/7988643/crash.report.txt)

**Comment by Urmus-dev** [comment]
Same thing here. Server crash when nobody was playing, same error
[crash-2022-05-20_20.52.42-server.txt](https://github.com/BuiltBrokenModding/AI-Improvements/files/8744672/crash-2022-05-20_20.52.42-server.txt)
.

**Comment by DarkGuardsman** [comment]
@bl4ckscor3 can you look into this one, likely a simple NPE check is needed due to other mods modifying default fields

**Comment by bl4ckscor3** [comment]
Ah, sorry, I forgot about this.

**Comment by simeonpfeiffer** [comment]
Thank you!
