### ISSUE TITLE
1.16.5 AI Improvements makes guard villagers NOT spawn at all, completely breaks the mod

### ISSUE THREAD

**Issue by JetpackRescue** [BuiltBrokenModding/AI-Improvements#22]
Latest version of both ai improvements and guard villagers mod

https://www.curseforge.com/minecraft/mc-mods/guard-villagers

Guard villagers don't spawn at all with AI improvements installed

forge 26.2.33
mc 1.16.5

**Comment by bl4ckscor3** [comment]
With just using Guard Villagers and AI Improvements, I cannot reproduce this. Are you using the default configuration files?

**Comment by DarkGuardsman** [comment]
I'm not seeing how we could be causing this... as AI improvements does not modify spawning.
