### ISSUE TITLE
problem with server ram

### ISSUE THREAD

**Issue by TainanRezende** [BuiltBrokenModding/AI-Improvements#23]
hi, I have a server with mods and I use your mod to improve performance and I am having a problem with excessive memory usage due to your mod, what happens is the following without the mod the server loses a lot of tps performance and with it as per we are exploring and playing normal and the server goes from 10gb easy and the normal is to stay at 6gb.

used modpack: https://www.curseforge.com/minecraft/modpacks/techmagic-4/files

obs: the preformant on the server I use the performant-1.16.2-5-3.98m.jar version, I haven't updated the curse until I actually solve the ram problem

**Comment by DarkGuardsman** [comment]
We will need more info then a hunch it is our mod. As we do not do anything in the mod that would use that much ram. Most of the changes in the mod are replacing existing AI objects with similar copies. Which shouldn't cause problems unless there is another mod spamming entity spawns.

**Comment by TainanRezende** [comment]
https://gist.github.com/TainanRezende/5f65b366bb887ed5b8eabc8e131b73d7

these are the logs of this exact moment
![image](https://user-images.githubusercontent.com/86209504/174677859-8bbf6010-5fa5-466e-8aa5-e7ca45e64be3.png)

I put the server to restart every 4 hours so I don't have time to get to 10gb so I don't crash go back in time

**Comment by TainanRezende** [comment]
https://gist.github.com/TainanRezende/5f65b366bb887ed5b8eabc8e131b73d7

these are the logs of this exact moment
![image](https://user-images.githubusercontent.com/86209504/174677859-8bbf6010-5fa5-466e-8aa5-e7ca45e64be3.png)

I put the server to restart every 4 hours so I don't have time to get to 10gb so I don't crash go back in time

**Comment by TainanRezende** [comment]
sorry for closing the comment line I clicked by mistake I have no experience

**Comment by DarkGuardsman** [comment]
I'm not seeing anything specific, I do see some random spam like `[20Jun2022 17:16:25.077] [Server thread/WARN] [net.minecraft.tileentity.TileEntity/]: Block entity invalid: minecraft:chest` but not sure what that is on about. Guessing some extra debug provided by either forge or some mod you have installed. I think I would need to know more of what is happening in the game world. As well if you could get some type of performance log showing what is using the RAM. VisualVM is what we usually use for profiling the game. It has an option to export RAM by class name and could help ID data types. If AI improvements is the cause we should see one our classes show up or at minimal one of the data types used in the AIs.

 https://www.baeldung.com/java-profilers

@bl4ckscor3 you see anything useful in the log? As I know you maintain for the newer version more than I do.

**Comment by bl4ckscor3** [comment]
As you said, there is nothing out of the ordinary in the log regarding AI Improvements. We would need a memory profiler log to be able to say anything more.
Sidenote: The log entry you mentioned is a vanilla thing, saying that the block at the position of the tile entity is not a block that is allowed to have a tile entity of that type (in this case minecraft:chest).

**Comment by TainanRezende** [comment]
look i apologize for bothering you, but two and a deeper investigation i saw that it is the "performant" mod that caused the ram problem, thank you very much for your attention and help,

**Comment by DarkGuardsman** [comment]
No worries, it can be hard to tell which mods are causing problems.
