### ISSUE TITLE
Cured/spawned villager keep walking into the sea and die

### ISSUE THREAD

**Issue by babacon88** [BuiltBrokenModding/AI-Improvements#27]
I dont know what is happening and whether or not this is from this mod.
My villagers keep swimming into open ocean and die
I tried following them but they wont stop swimming
I dont have anywhere else to ask this strange behavivor

**Comment by bl4ckscor3** [comment]
Does this still happen if you remove AI Improvements?

**Comment by DarkGuardsman** [comment]
Closing, re-open when we get more info. As mod does not interact with villagers currently.
