### ISSUE TITLE
unclear license

### ISSUE THREAD

**Issue by DioEgizio** [BuiltBrokenModding/AI-Improvements#28]
In the CF page it says that this mod is ARR, but source here is "MIT but applies only to code"
What's the not code part here?

**Comment by bl4ckscor3** [comment]
The not-code part are assets, of which AI Improvements has none. They may fall under a different license, which is the case for ICBM Classic, for example. I'm unsure about why the CF page says "ARR". It could either be meaning the binaries are ARR, or it was simply overlooked to set the proper license for the project.

**Comment by DarkGuardsman** [comment]
Downloads on CF are ARR to prevent repost sites from stealing them.
