### ISSUE TITLE
Question about mod blocks & pathfind

### ISSUE THREAD

**Issue by Psychodeus** [BuiltBrokenModding/AI-Improvements#34]
![image](https://user-images.githubusercontent.com/93028949/196243590-998e0327-e7fc-4659-85c7-8bdbe92ba55a.png)

I used NiceMod for new building block, but somehow it screwed pathfind of villagers, will this mod solve the pathfinding problem since it says it will implement "**Multithreading for AI nav pathfinder**" on the upcoming update?

**Comment by DarkGuardsman** [comment]
Unlikely, most changes we target are for performance improvements of the game. Since this may be modded interaction it is even less likely. As it is possible the mod `NiceMod` did something funky with their block collisions.

**Comment by Psychodeus** [comment]
![image](https://user-images.githubusercontent.com/93028949/197324286-7540ae86-22b2-4ba4-92ac-7e8821b83afc.png)

But, could you please take a [look](https://modrinth.com/mod/nicemod) and give a little hand?
![pweeese](https://user-images.githubusercontent.com/93028949/197324360-ac4901c1-5dd5-454e-addf-6c5ea726278c.png)

**Comment by bl4ckscor3** [comment]
Didn't take me a minute to find. Here is the problem, this method needs to be properly overriden to return false, or completely removed, for all the blocks where pathfinding breaks. https://github.com/MIUNO/NiceMod/blob/46f3ac28070163cc7b04727c06305897a4d3b393/src/main/java/ru/miuno/nicemod/blocks/block_types/HorizontalHalf.java#L99-L102

**Comment by Psychodeus** [comment]
THANK YOUUU
![aYJ5eADZ_700w_0](https://user-images.githubusercontent.com/93028949/197332407-eb5dee57-ffbc-4a10-8d70-3800d4a13da6.jpg)
