### ISSUE TITLE
Villagers does not close door when they go to sleep.

### ISSUE THREAD

**Issue by isuke01** [BuiltBrokenModding/AI-Improvements#35]
Minecraft `version: 1.19.3`
Mod version: [AI-Improvements-1.19.2/.3-0.5.2.jar](https://www.curseforge.com/minecraft/mc-mods/ai-improvements/files/4019127)
Fabric: `fabric-server-mc.1.19.3-loader.0.14.12`

Hi, 
I noticed with the mod activated the villagers does not close doors when the go to sleep.
So they get slaughtered super quickly by zombies :|

**Comment by bl4ckscor3** [comment]
AI Improvements is not a Fabric mod. AI Improvements does not change villager behavior like that. For all intents and purposes, AI Improvements cannot be the cause of this issue.
