### ISSUE TITLE
Compatibility for vampirism mod

### ISSUE THREAD

**Issue by Thunderrock424242** [BuiltBrokenModding/AI-Improvements#38]
When your a vampire without ai improvements mobs that spawn at night don't attack you. But ai improvements changes the ai so they attack you no matter what.

**Comment by DarkGuardsman** [comment]
We don't modify combat AIs, only thing enabled by default is improved math for AI aiming. All other settings have to be enabled manually in the config. So if combat is being changed it could be the vampirism mod failing.

**Comment by Thunderrock424242** [comment]
Alr thank you
