### ISSUE TITLE
Worst pathfinding performance on Thermos 1.7.10 server

### ISSUE THREAD

**Issue by wConstruct** [BuiltBrokenModding/AI-Improvements#5]
Sometimes when loaded > 2800 entities on server TPS falls down:

![image](https://user-images.githubusercontent.com/34898907/41190374-0756d158-6bff-11e8-804f-25009011aea7.png)

Does the mod fix this problem?

Thermos server 58 build https://github.com/CyberdyneCC/Thermos/releases
AIImprovements-1.7.10-0.0.1b19-dev

**Comment by DarkGuardsman** [comment]
At the moment AI improves only changes some minor AI stuff. Such as head look doing a lot of trig math wasting CPU cycles.

That being said, pathfinding is on the planned feature list. Starting first with reducing how often pathing is done and second with threading it to remove usage off the main game loop.
